# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\mediscara\extras\widgets\statusbar_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatusBarWidget(object):
    def setupUi(self, StatusBarWidget):
        StatusBarWidget.setObjectName("StatusBarWidget")
        StatusBarWidget.resize(301, 38)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StatusBarWidget.sizePolicy().hasHeightForWidth())
        StatusBarWidget.setSizePolicy(sizePolicy)
        StatusBarWidget.setMaximumSize(QtCore.QSize(16777215, 10000000))
        self.horizontalLayout = QtWidgets.QHBoxLayout(StatusBarWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(StatusBarWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_db_connected = QtWidgets.QLabel(StatusBarWidget)
        self.label_db_connected.setMinimumSize(QtCore.QSize(100, 20))
        self.label_db_connected.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_db_connected.setAlignment(QtCore.Qt.AlignCenter)
        self.label_db_connected.setObjectName("label_db_connected")
        self.horizontalLayout.addWidget(self.label_db_connected)
        self.horizontalLayout.setStretch(0, 1)

        self.retranslateUi(StatusBarWidget)
        QtCore.QMetaObject.connectSlotsByName(StatusBarWidget)

    def retranslateUi(self, StatusBarWidget):
        _translate = QtCore.QCoreApplication.translate
        StatusBarWidget.setWindowTitle(_translate("StatusBarWidget", "Form"))
        self.label.setText(_translate("StatusBarWidget", "MySQL adatbázis csatlakozási állapot"))
        self.label_db_connected.setText(_translate("StatusBarWidget", "Nincs csatlakozva"))
