# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\gyurc\OneDrive\Dokumentumok\VSCodeProjects\mediscara\manager\src\manager\gui\layout\collaborative.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_collaborativeWindow(object):
    def setupUi(self, collaborativeWindow):
        collaborativeWindow.setObjectName("collaborativeWindow")
        collaborativeWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(collaborativeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.list_widget.setObjectName("list_widget")
        self.verticalLayout.addWidget(self.list_widget)
        collaborativeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(collaborativeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        collaborativeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(collaborativeWindow)
        self.statusbar.setObjectName("statusbar")
        collaborativeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(collaborativeWindow)
        QtCore.QMetaObject.connectSlotsByName(collaborativeWindow)

    def retranslateUi(self, collaborativeWindow):
        _translate = QtCore.QCoreApplication.translate
        collaborativeWindow.setWindowTitle(_translate("collaborativeWindow", "MainWindow"))
