# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\gyurc\OneDrive\Dokumentumok\VSCodeProjects\mediscara\manager\src\manager\gui\layout\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.web_widget = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.web_widget.setObjectName("web_widget")
        self.verticalLayout.addWidget(self.web_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_manage_cells = QtWidgets.QMenu(self.menuFile)
        self.menu_manage_cells.setObjectName("menu_manage_cells")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCell_1 = QtWidgets.QAction(MainWindow)
        self.actionCell_1.setObjectName("actionCell_1")
        self.actionCell_2 = QtWidgets.QAction(MainWindow)
        self.actionCell_2.setObjectName("actionCell_2")
        self.action_collaborative = QtWidgets.QAction(MainWindow)
        self.action_collaborative.setObjectName("action_collaborative")
        self.action_industrial = QtWidgets.QAction(MainWindow)
        self.action_industrial.setObjectName("action_industrial")
        self.action_preferences = QtWidgets.QAction(MainWindow)
        self.action_preferences.setObjectName("action_preferences")
        self.menu_manage_cells.addAction(self.action_collaborative)
        self.menu_manage_cells.addAction(self.action_industrial)
        self.menuFile.addAction(self.menu_manage_cells.menuAction())
        self.menuFile.addAction(self.action_preferences)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MEDISCARA Manager"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menu_manage_cells.setTitle(_translate("MainWindow", "Manage Cells..."))
        self.actionCell_1.setText(_translate("MainWindow", "Cell 1"))
        self.actionCell_2.setText(_translate("MainWindow", "Cell 2"))
        self.action_collaborative.setText(_translate("MainWindow", "Collaborative"))
        self.action_industrial.setText(_translate("MainWindow", "Industrial"))
        self.action_preferences.setText(_translate("MainWindow", "Preferences"))


from PyQt5 import QtWebEngineWidgets
