# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\gyurc\OneDrive\Dokumentumok\VSCodeProjects\mediscara\manager\src\manager\gui\layout\industrial_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListItem(object):
    def setupUi(self, ListItem):
        ListItem.setObjectName("ListItem")
        ListItem.resize(400, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ListItem.sizePolicy().hasHeightForWidth())
        ListItem.setSizePolicy(sizePolicy)
        ListItem.setMinimumSize(QtCore.QSize(0, 100))
        ListItem.setStyleSheet("QWidget#ListItem {\n" "    border: 1px solid black;\n" "    border-radius: 6px;\n" "}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(ListItem)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_inc_type = QtWidgets.QLabel(ListItem)
        self.label_inc_type.setObjectName("label_inc_type")
        self.horizontalLayout.addWidget(self.label_inc_type)
        self.label_count = QtWidgets.QLabel(ListItem)
        self.label_count.setObjectName("label_count")
        self.horizontalLayout.addWidget(self.label_count)
        self.label_remaining = QtWidgets.QLabel(ListItem)
        self.label_remaining.setObjectName("label_remaining")
        self.horizontalLayout.addWidget(self.label_remaining)

        self.retranslateUi(ListItem)
        QtCore.QMetaObject.connectSlotsByName(ListItem)

    def retranslateUi(self, ListItem):
        _translate = QtCore.QCoreApplication.translate
        ListItem.setWindowTitle(_translate("ListItem", "Form"))
        self.label_inc_type.setText(_translate("ListItem", "Incubator type"))
        self.label_count.setText(_translate("ListItem", "Production Count"))
        self.label_remaining.setText(_translate("ListItem", "Remaining"))
