# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\gyurc\OneDrive\Dokumentumok\VSCodeProjects\mediscara\manager\src\manager\gui\layout\industrial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_industrialWindow(object):
    def setupUi(self, industrialWindow):
        industrialWindow.setObjectName("industrialWindow")
        industrialWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(industrialWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.list_widget.setObjectName("list_widget")
        self.verticalLayout.addWidget(self.list_widget)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_edit_inc_type = QtWidgets.QLineEdit(self.frame)
        self.line_edit_inc_type.setObjectName("line_edit_inc_type")
        self.horizontalLayout.addWidget(self.line_edit_inc_type)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinbox_count = QtWidgets.QSpinBox(self.frame)
        self.spinbox_count.setMinimumSize(QtCore.QSize(50, 0))
        self.spinbox_count.setObjectName("spinbox_count")
        self.horizontalLayout.addWidget(self.spinbox_count)
        self.button_publish = QtWidgets.QPushButton(self.frame)
        self.button_publish.setObjectName("button_publish")
        self.horizontalLayout.addWidget(self.button_publish)
        self.verticalLayout.addWidget(self.frame)
        industrialWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(industrialWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        industrialWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(industrialWindow)
        self.statusbar.setObjectName("statusbar")
        industrialWindow.setStatusBar(self.statusbar)

        self.retranslateUi(industrialWindow)
        QtCore.QMetaObject.connectSlotsByName(industrialWindow)

    def retranslateUi(self, industrialWindow):
        _translate = QtCore.QCoreApplication.translate
        industrialWindow.setWindowTitle(_translate("industrialWindow", "Industral Manager"))
        self.label.setText(_translate("industrialWindow", "Incubator Type"))
        self.label_2.setText(_translate("industrialWindow", "Production Count"))
        self.button_publish.setText(_translate("industrialWindow", "Publish"))
