# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\gyurc\OneDrive\Dokumentumok\VSCodeProjects\mediscara\manager\src\manager\gui\layout\preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_preferencesWindow(object):
    def setupUi(self, preferencesWindow):
        preferencesWindow.setObjectName("preferencesWindow")
        preferencesWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        preferencesWindow.resize(255, 260)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(preferencesWindow.sizePolicy().hasHeightForWidth())
        preferencesWindow.setSizePolicy(sizePolicy)
        preferencesWindow.setMinimumSize(QtCore.QSize(255, 260))
        preferencesWindow.setMaximumSize(QtCore.QSize(255, 260))
        self.centralwidget = QtWidgets.QWidget(preferencesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(6, 6, 6, 6)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_edit_server_address = QtWidgets.QLineEdit(self.frame)
        self.line_edit_server_address.setObjectName("line_edit_server_address")
        self.horizontalLayout_2.addWidget(self.line_edit_server_address)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        self.button_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        preferencesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(preferencesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 255, 21))
        self.menubar.setObjectName("menubar")
        preferencesWindow.setMenuBar(self.menubar)

        self.retranslateUi(preferencesWindow)
        QtCore.QMetaObject.connectSlotsByName(preferencesWindow)

    def retranslateUi(self, preferencesWindow):
        _translate = QtCore.QCoreApplication.translate
        preferencesWindow.setWindowTitle(_translate("preferencesWindow", "Preferences"))
        self.label.setText(_translate("preferencesWindow", "Server Address"))
        self.button_save.setText(_translate("preferencesWindow", "Save"))
        self.button_cancel.setText(_translate("preferencesWindow", "Cancel"))
