# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\gyurc\OneDrive\Dokumentumok\VSCodeProjects\mediscara\manager\src\manager\gui\layout\preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_preferencesWindow(object):
    def setupUi(self, preferencesWindow):
        preferencesWindow.setObjectName("preferencesWindow")
        preferencesWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(preferencesWindow)
        self.centralwidget.setObjectName("centralwidget")
        preferencesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(preferencesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        preferencesWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(preferencesWindow)
        self.statusbar.setObjectName("statusbar")
        preferencesWindow.setStatusBar(self.statusbar)

        self.retranslateUi(preferencesWindow)
        QtCore.QMetaObject.connectSlotsByName(preferencesWindow)

    def retranslateUi(self, preferencesWindow):
        _translate = QtCore.QCoreApplication.translate
        preferencesWindow.setWindowTitle(_translate("preferencesWindow", "Preferences"))
