#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'mediscara==0.0.2','console_scripts','robot1_node'
__requires__ = 'mediscara==0.0.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('mediscara==0.0.2', 'console_scripts', 'robot1_node')()
    )
