---
version: "3"

services:
  mongo:
    image: mongo:latest
    command: --nojournal

  orion:
    image: fiware/orion:latest
    container_name: orion-container
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbhost mongo
    healthcheck:
        test: curl --fail -s http://orion:1026/version || exit 1 

  crate-db:
    image: crate:3.3.2
    ports:
      - "4200:4200"
      - "4300:4300"
      - "5432:5432"

  quantum-leap:
    image: fiware/quantum-leap:latest
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      CRATE_HOST: crate-db

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3003:3000"
    depends_on:
      - crate-db
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-worldmap-panel



