# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '\\wsl$\Ubuntu-20.04\home\ppuska\mediscara_ws\src\mediscara\mediscara\scripts\widgets\layout\collab_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CollabControlWidget(object):
    def setupUi(self, CollabControlWidget):
        CollabControlWidget.setObjectName("CollabControlWidget")
        CollabControlWidget.resize(704, 496)
        CollabControlWidget.setStyleSheet("QLabel {\n"
"    border-radius: 10px;\n"
"    background-color: rgba(0, 255, 127, 128);\n"
"}\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(CollabControlWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(CollabControlWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label_remaining_time = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_remaining_time.sizePolicy().hasHeightForWidth())
        self.label_remaining_time.setSizePolicy(sizePolicy)
        self.label_remaining_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remaining_time.setObjectName("label_remaining_time")
        self.gridLayout.addWidget(self.label_remaining_time, 1, 1, 1, 2)
        self.button_home = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_home.sizePolicy().hasHeightForWidth())
        self.button_home.setSizePolicy(sizePolicy)
        self.button_home.setMinimumSize(QtCore.QSize(0, 60))
        self.button_home.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(108, 210, 240, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(57, 138, 163, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.button_home.setObjectName("button_home")
        self.gridLayout.addWidget(self.button_home, 1, 0, 1, 1)
        self.label_pcb_ok = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pcb_ok.sizePolicy().hasHeightForWidth())
        self.label_pcb_ok.setSizePolicy(sizePolicy)
        self.label_pcb_ok.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pcb_ok.setObjectName("label_pcb_ok")
        self.gridLayout.addWidget(self.label_pcb_ok, 2, 2, 1, 1)
        self.label_message = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_message.sizePolicy().hasHeightForWidth())
        self.label_message.setSizePolicy(sizePolicy)
        self.label_message.setObjectName("label_message")
        self.gridLayout.addWidget(self.label_message, 4, 0, 1, 3)
        self.button_start_session = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start_session.sizePolicy().hasHeightForWidth())
        self.button_start_session.setSizePolicy(sizePolicy)
        self.button_start_session.setMinimumSize(QtCore.QSize(0, 60))
        self.button_start_session.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(92, 212, 76, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(88, 198, 71, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.button_start_session.setObjectName("button_start_session")
        self.gridLayout.addWidget(self.button_start_session, 0, 0, 1, 1)
        self.label_label_ok = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_label_ok.sizePolicy().hasHeightForWidth())
        self.label_label_ok.setSizePolicy(sizePolicy)
        self.label_label_ok.setAlignment(QtCore.Qt.AlignCenter)
        self.label_label_ok.setObjectName("label_label_ok")
        self.gridLayout.addWidget(self.label_label_ok, 3, 2, 1, 1)
        self.button_measure_label = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_measure_label.sizePolicy().hasHeightForWidth())
        self.button_measure_label.setSizePolicy(sizePolicy)
        self.button_measure_label.setMinimumSize(QtCore.QSize(0, 30))
        self.button_measure_label.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(240, 62, 114, 128), stop:1 rgba(255, 255, 255, 128));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(216, 56, 104, 128), stop:1 rgba(255, 255, 255, 128));\n"
"}\n"
"")
        self.button_measure_label.setObjectName("button_measure_label")
        self.gridLayout.addWidget(self.button_measure_label, 2, 1, 2, 1)
        self.button_end_session = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_end_session.sizePolicy().hasHeightForWidth())
        self.button_end_session.setSizePolicy(sizePolicy)
        self.button_end_session.setMinimumSize(QtCore.QSize(0, 60))
        self.button_end_session.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(240, 62, 114, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(216, 56, 104, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.button_end_session.setObjectName("button_end_session")
        self.gridLayout.addWidget(self.button_end_session, 0, 2, 1, 1)
        self.button_pause = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pause.sizePolicy().hasHeightForWidth())
        self.button_pause.setSizePolicy(sizePolicy)
        self.button_pause.setMinimumSize(QtCore.QSize(0, 60))
        self.button_pause.setObjectName("button_pause")
        self.gridLayout.addWidget(self.button_pause, 0, 1, 1, 1)
        self.button_measure_pcb = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_measure_pcb.sizePolicy().hasHeightForWidth())
        self.button_measure_pcb.setSizePolicy(sizePolicy)
        self.button_measure_pcb.setMinimumSize(QtCore.QSize(0, 30))
        self.button_measure_pcb.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(108, 210, 240, 128), stop:1 rgba(255, 255, 255, 128));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(57, 138, 163, 128), stop:1 rgba(255, 255, 255, 128));\n"
"}")
        self.button_measure_pcb.setObjectName("button_measure_pcb")
        self.gridLayout.addWidget(self.button_measure_pcb, 2, 0, 2, 1)
        self.label_maintenance = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_maintenance.sizePolicy().hasHeightForWidth())
        self.label_maintenance.setSizePolicy(sizePolicy)
        self.label_maintenance.setObjectName("label_maintenance")
        self.gridLayout.addWidget(self.label_maintenance, 5, 0, 1, 3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(CollabControlWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_start_session_rob = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start_session_rob.sizePolicy().hasHeightForWidth())
        self.button_start_session_rob.setSizePolicy(sizePolicy)
        self.button_start_session_rob.setMinimumSize(QtCore.QSize(0, 60))
        self.button_start_session_rob.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(92, 212, 76, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(88, 198, 71, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.button_start_session_rob.setObjectName("button_start_session_rob")
        self.gridLayout_2.addWidget(self.button_start_session_rob, 0, 0, 1, 1)
        self.button_home_rob = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_home_rob.sizePolicy().hasHeightForWidth())
        self.button_home_rob.setSizePolicy(sizePolicy)
        self.button_home_rob.setMinimumSize(QtCore.QSize(0, 60))
        self.button_home_rob.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(108, 210, 240, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(57, 138, 163, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.button_home_rob.setObjectName("button_home_rob")
        self.gridLayout_2.addWidget(self.button_home_rob, 3, 0, 1, 1)
        self.button_pause_rob = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pause_rob.sizePolicy().hasHeightForWidth())
        self.button_pause_rob.setSizePolicy(sizePolicy)
        self.button_pause_rob.setMinimumSize(QtCore.QSize(0, 60))
        self.button_pause_rob.setObjectName("button_pause_rob")
        self.gridLayout_2.addWidget(self.button_pause_rob, 0, 1, 1, 1)
        self.button_end_session_rob = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_end_session_rob.sizePolicy().hasHeightForWidth())
        self.button_end_session_rob.setSizePolicy(sizePolicy)
        self.button_end_session_rob.setMinimumSize(QtCore.QSize(0, 60))
        self.button_end_session_rob.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(240, 62, 114, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(216, 56, 104, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.button_end_session_rob.setObjectName("button_end_session_rob")
        self.gridLayout_2.addWidget(self.button_end_session_rob, 0, 2, 1, 1)
        self.label_maintenance_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_maintenance_2.sizePolicy().hasHeightForWidth())
        self.label_maintenance_2.setSizePolicy(sizePolicy)
        self.label_maintenance_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_maintenance_2.setObjectName("label_maintenance_2")
        self.gridLayout_2.addWidget(self.label_maintenance_2, 3, 1, 1, 2)
        self.label_message_rob = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_message_rob.sizePolicy().hasHeightForWidth())
        self.label_message_rob.setSizePolicy(sizePolicy)
        self.label_message_rob.setObjectName("label_message_rob")
        self.gridLayout_2.addWidget(self.label_message_rob, 7, 0, 1, 3)
        self.label_maintenance_rob = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_maintenance_rob.sizePolicy().hasHeightForWidth())
        self.label_maintenance_rob.setSizePolicy(sizePolicy)
        self.label_maintenance_rob.setObjectName("label_maintenance_rob")
        self.gridLayout_2.addWidget(self.label_maintenance_rob, 8, 0, 1, 3)
        self.button_start_marking = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start_marking.sizePolicy().hasHeightForWidth())
        self.button_start_marking.setSizePolicy(sizePolicy)
        self.button_start_marking.setMinimumSize(QtCore.QSize(0, 30))
        self.button_start_marking.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(240, 62, 114, 128), stop:1 rgba(255, 255, 255, 128));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(216, 56, 104, 128), stop:1 rgba(255, 255, 255, 128));\n"
"}\n"
"")
        self.button_start_marking.setObjectName("button_start_marking")
        self.gridLayout_2.addWidget(self.button_start_marking, 4, 0, 2, 2)
        self.label_marking_ok = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_marking_ok.sizePolicy().hasHeightForWidth())
        self.label_marking_ok.setSizePolicy(sizePolicy)
        self.label_marking_ok.setAlignment(QtCore.Qt.AlignCenter)
        self.label_marking_ok.setObjectName("label_marking_ok")
        self.gridLayout_2.addWidget(self.label_marking_ok, 4, 2, 2, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(CollabControlWidget)
        QtCore.QMetaObject.connectSlotsByName(CollabControlWidget)

    def retranslateUi(self, CollabControlWidget):
        _translate = QtCore.QCoreApplication.translate
        CollabControlWidget.setWindowTitle(_translate("CollabControlWidget", "Form"))
        self.groupBox.setTitle(_translate("CollabControlWidget", "VISION"))
        self.label_remaining_time.setText(_translate("CollabControlWidget", "Remaining time: "))
        self.button_home.setText(_translate("CollabControlWidget", "HOME"))
        self.label_pcb_ok.setText(_translate("CollabControlWidget", "PCB Measure:\n"
"OK"))
        self.label_message.setText(_translate("CollabControlWidget", "TextLabel"))
        self.button_start_session.setText(_translate("CollabControlWidget", "Start Session"))
        self.label_label_ok.setText(_translate("CollabControlWidget", "Label Measure:\n"
"OK"))
        self.button_measure_label.setText(_translate("CollabControlWidget", "Measure Label"))
        self.button_end_session.setText(_translate("CollabControlWidget", "End Session"))
        self.button_pause.setText(_translate("CollabControlWidget", "Pause/Resume"))
        self.button_measure_pcb.setText(_translate("CollabControlWidget", "Measure PCB"))
        self.label_maintenance.setText(_translate("CollabControlWidget", "TextLabel"))
        self.groupBox_2.setTitle(_translate("CollabControlWidget", "MARKING SYSTEM"))
        self.button_start_session_rob.setText(_translate("CollabControlWidget", "Start Session"))
        self.button_home_rob.setText(_translate("CollabControlWidget", "HOME"))
        self.button_pause_rob.setText(_translate("CollabControlWidget", "Pause/Resume"))
        self.button_end_session_rob.setText(_translate("CollabControlWidget", "End Session"))
        self.label_maintenance_2.setText(_translate("CollabControlWidget", "Remaining time: "))
        self.label_message_rob.setText(_translate("CollabControlWidget", "TextLabel"))
        self.label_maintenance_rob.setText(_translate("CollabControlWidget", "TextLabel"))
        self.button_start_marking.setText(_translate("CollabControlWidget", "Start Marking"))
        self.label_marking_ok.setText(_translate("CollabControlWidget", "Marking:\n"
"OK"))
from . import res_rc
