# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotic_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoboticControlWidget(object):
    def setupUi(self, RoboticControlWidget):
        RoboticControlWidget.setObjectName("RoboticControlWidget")
        RoboticControlWidget.resize(746, 536)
        RoboticControlWidget.setStyleSheet(
            "QLabel {\n" "    border: 1px solid black;\n" "    border-radius: 7px;\n" "}"
        )
        self.gridLayout = QtWidgets.QGridLayout(RoboticControlWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.button_home = QtWidgets.QPushButton(RoboticControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_home.sizePolicy().hasHeightForWidth())
        self.button_home.setSizePolicy(sizePolicy)
        self.button_home.setMinimumSize(QtCore.QSize(0, 100))
        self.button_home.setStyleSheet(
            "QPushButton {\n"
            "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(81, 186, 246, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(34, 142, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "}"
        )
        self.button_home.setObjectName("button_home")
        self.gridLayout.addWidget(self.button_home, 1, 0, 1, 1)
        self.button_pause = QtWidgets.QPushButton(RoboticControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pause.sizePolicy().hasHeightForWidth())
        self.button_pause.setSizePolicy(sizePolicy)
        self.button_pause.setMinimumSize(QtCore.QSize(0, 100))
        self.button_pause.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(246, 223, 134);\n"
            "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(246, 223, 146, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(216, 179, 41, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "}"
        )
        self.button_pause.setObjectName("button_pause")
        self.gridLayout.addWidget(self.button_pause, 0, 1, 1, 1)
        self.button_end_session = QtWidgets.QPushButton(RoboticControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_end_session.sizePolicy().hasHeightForWidth())
        self.button_end_session.setSizePolicy(sizePolicy)
        self.button_end_session.setMinimumSize(QtCore.QSize(0, 100))
        self.button_end_session.setStyleSheet(
            "QPushButton:!pressed {\n"
            "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(240, 62, 114, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(216, 56, 104, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "}\n"
            ""
        )
        self.button_end_session.setObjectName("button_end_session")
        self.gridLayout.addWidget(self.button_end_session, 0, 2, 1, 1)
        self.button_start_session = QtWidgets.QPushButton(RoboticControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start_session.sizePolicy().hasHeightForWidth())
        self.button_start_session.setSizePolicy(sizePolicy)
        self.button_start_session.setMinimumSize(QtCore.QSize(0, 100))
        self.button_start_session.setStyleSheet(
            "QPushButton:!pressed {\n"
            "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(92, 212, 76, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(88, 198, 71, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "}"
        )
        self.button_start_session.setObjectName("button_start_session")
        self.gridLayout.addWidget(self.button_start_session, 0, 0, 1, 1)
        self.button_start_cutting = QtWidgets.QPushButton(RoboticControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start_cutting.sizePolicy().hasHeightForWidth())
        self.button_start_cutting.setSizePolicy(sizePolicy)
        self.button_start_cutting.setMinimumSize(QtCore.QSize(0, 100))
        self.button_start_cutting.setStyleSheet(
            "QPushButton {\n"
            "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(246, 148, 81, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(224, 111, 34, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "\n"
            "}"
        )
        self.button_start_cutting.setObjectName("button_start_cutting")
        self.gridLayout.addWidget(self.button_start_cutting, 2, 0, 1, 1)
        self.label_cutting = QtWidgets.QLabel(RoboticControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cutting.sizePolicy().hasHeightForWidth())
        self.label_cutting.setSizePolicy(sizePolicy)
        self.label_cutting.setObjectName("label_cutting")
        self.gridLayout.addWidget(self.label_cutting, 2, 1, 1, 2)
        self.label_time_remaining = QtWidgets.QLabel(RoboticControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_remaining.sizePolicy().hasHeightForWidth())
        self.label_time_remaining.setSizePolicy(sizePolicy)
        self.label_time_remaining.setObjectName("label_time_remaining")
        self.gridLayout.addWidget(self.label_time_remaining, 1, 2, 1, 1)

        self.retranslateUi(RoboticControlWidget)
        QtCore.QMetaObject.connectSlotsByName(RoboticControlWidget)

    def retranslateUi(self, RoboticControlWidget):
        _translate = QtCore.QCoreApplication.translate
        RoboticControlWidget.setWindowTitle(_translate("RoboticControlWidget", "Form"))
        self.button_home.setText(_translate("RoboticControlWidget", "HOME"))
        self.button_pause.setText(_translate("RoboticControlWidget", "Pause"))
        self.button_end_session.setText(_translate("RoboticControlWidget", "End Session"))
        self.button_start_session.setText(_translate("RoboticControlWidget", "Start Session"))
        self.button_start_cutting.setText(_translate("RoboticControlWidget", "Start Cutting"))
        self.label_cutting.setText(_translate("RoboticControlWidget", "TextLabel"))
        self.label_time_remaining.setText(_translate("RoboticControlWidget", "TextLabel"))
