# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotic_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoboticInfoTab(object):
    def setupUi(self, RoboticInfoTab):
        RoboticInfoTab.setObjectName("RoboticInfoTab")
        RoboticInfoTab.resize(710, 626)
        RoboticInfoTab.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(RoboticInfoTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(RoboticInfoTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_performance = QtWidgets.QLabel(self.groupBox)
        self.label_performance.setMinimumSize(QtCore.QSize(0, 60))
        self.label_performance.setObjectName("label_performance")
        self.gridLayout.addWidget(self.label_performance, 1, 1, 1, 1)
        self.label_quality = QtWidgets.QLabel(self.groupBox)
        self.label_quality.setMinimumSize(QtCore.QSize(0, 60))
        self.label_quality.setObjectName("label_quality")
        self.gridLayout.addWidget(self.label_quality, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(0, 60))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(0, 60))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_availability = QtWidgets.QLabel(self.groupBox)
        self.label_availability.setMinimumSize(QtCore.QSize(0, 60))
        self.label_availability.setObjectName("label_availability")
        self.gridLayout.addWidget(self.label_availability, 0, 1, 1, 1)
        self.label_oee = QtWidgets.QLabel(self.groupBox)
        self.label_oee.setMinimumSize(QtCore.QSize(0, 60))
        self.label_oee.setObjectName("label_oee")
        self.gridLayout.addWidget(self.label_oee, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(RoboticInfoTab)
        self.frame.setStyleSheet("QLabel {\n"
"    border: 1px solid black;\n"
"    border-radius: 7px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_power = QtWidgets.QLabel(self.frame)
        self.label_power.setMinimumSize(QtCore.QSize(0, 50))
        self.label_power.setAlignment(QtCore.Qt.AlignCenter)
        self.label_power.setObjectName("label_power")
        self.verticalLayout_4.addWidget(self.label_power)
        self.label_running = QtWidgets.QLabel(self.frame)
        self.label_running.setMinimumSize(QtCore.QSize(0, 50))
        self.label_running.setAlignment(QtCore.Qt.AlignCenter)
        self.label_running.setObjectName("label_running")
        self.verticalLayout_4.addWidget(self.label_running)
        self.label_waiting = QtWidgets.QLabel(self.frame)
        self.label_waiting.setMinimumSize(QtCore.QSize(0, 50))
        self.label_waiting.setAlignment(QtCore.Qt.AlignCenter)
        self.label_waiting.setObjectName("label_waiting")
        self.verticalLayout_4.addWidget(self.label_waiting)
        self.label_error = QtWidgets.QLabel(self.frame)
        self.label_error.setMinimumSize(QtCore.QSize(0, 50))
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.verticalLayout_4.addWidget(self.label_error)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(RoboticInfoTab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.frame_2 = QtWidgets.QFrame(RoboticInfoTab)
        self.frame_2.setStyleSheet("QFrame {\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;\n"
"\n"
"    background-color: rgba(85, 170, 255, 128);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: rgba(85, 170, 127, 128);\n"
"}\n"
"\n"
"QLabel {\n"
"    border: \"\";\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setStyleSheet("")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_current_job = QtWidgets.QLabel(self.frame_3)
        self.label_current_job.setObjectName("label_current_job")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_current_job)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_done_products = QtWidgets.QLabel(self.frame_3)
        self.label_done_products.setObjectName("label_done_products")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_done_products)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_remaining = QtWidgets.QLabel(self.frame_3)
        self.label_remaining.setObjectName("label_remaining")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_remaining)
        self.verticalLayout_2.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 128);\n"
"}\n"
"\n"
"QLabel {\n"
"    border: \"\";\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_job_in_progress = QtWidgets.QLabel(self.frame_4)
        self.label_job_in_progress.setObjectName("label_job_in_progress")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_job_in_progress)
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_request_sent = QtWidgets.QLabel(self.frame_4)
        self.label_request_sent.setObjectName("label_request_sent")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_request_sent)
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_task = QtWidgets.QLabel(self.frame_4)
        self.label_task.setObjectName("label_task")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_task)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_global_error = QtWidgets.QLabel(RoboticInfoTab)
        self.label_global_error.setStyleSheet("QLabel {\n"
"    border: 1px solid black;\n"
"    border-radius: 7px;\n"
"\n"
"    background-color: rgba(157, 157, 157, 128);\n"
"}")
        self.label_global_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_global_error.setObjectName("label_global_error")
        self.verticalLayout_3.addWidget(self.label_global_error)
        self.verticalLayout_3.setStretch(0, 4)
        self.verticalLayout_3.setStretch(1, 1)

        self.retranslateUi(RoboticInfoTab)
        QtCore.QMetaObject.connectSlotsByName(RoboticInfoTab)

    def retranslateUi(self, RoboticInfoTab):
        _translate = QtCore.QCoreApplication.translate
        RoboticInfoTab.setWindowTitle(_translate("RoboticInfoTab", "Form"))
        self.groupBox.setTitle(_translate("RoboticInfoTab", "KPI"))
        self.label.setText(_translate("RoboticInfoTab", "Availability"))
        self.label_performance.setText(_translate("RoboticInfoTab", "TextLabel"))
        self.label_quality.setText(_translate("RoboticInfoTab", "TextLabel"))
        self.label_2.setText(_translate("RoboticInfoTab", "Performance"))
        self.label_7.setText(_translate("RoboticInfoTab", "Quality"))
        self.label_availability.setText(_translate("RoboticInfoTab", "TextLabel"))
        self.label_oee.setText(_translate("RoboticInfoTab", "TextLabel"))
        self.label_power.setText(_translate("RoboticInfoTab", "Powered ON"))
        self.label_running.setText(_translate("RoboticInfoTab", "Running"))
        self.label_waiting.setText(_translate("RoboticInfoTab", "Waiting"))
        self.label_error.setText(_translate("RoboticInfoTab", "Error"))
        self.label_3.setText(_translate("RoboticInfoTab", "Current Job:"))
        self.label_current_job.setText(_translate("RoboticInfoTab", "TextLabel"))
        self.label_5.setText(_translate("RoboticInfoTab", "Done & Good products"))
        self.label_done_products.setText(_translate("RoboticInfoTab", "TextLabel"))
        self.label_8.setText(_translate("RoboticInfoTab", "Remaining products:"))
        self.label_remaining.setText(_translate("RoboticInfoTab", "TextLabel"))
        self.label_10.setText(_translate("RoboticInfoTab", "Job in Progress"))
        self.label_job_in_progress.setText(_translate("RoboticInfoTab", "TextLabel"))
        self.label_12.setText(_translate("RoboticInfoTab", "Request sent for next job:"))
        self.label_request_sent.setText(_translate("RoboticInfoTab", "TextLabel"))
        self.label_15.setText(_translate("RoboticInfoTab", "Task:"))
        self.label_task.setText(_translate("RoboticInfoTab", "TextLabel"))
        self.label_global_error.setText(_translate("RoboticInfoTab", "TextLabel"))
