# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '\\wsl$\Ubuntu-20.04\home\ppuska\mediscara_ws\src\mediscara\mediscara\scripts\widgets\layout\statusbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatusBar(object):
    def setupUi(self, StatusBar):
        StatusBar.setObjectName("StatusBar")
        StatusBar.resize(320, 240)
        StatusBar.setStyleSheet("QLabel {\n" "    padding: 6px;\n" "}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(StatusBar)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_login = QtWidgets.QLabel(StatusBar)
        self.label_login.setObjectName("label_login")
        self.horizontalLayout.addWidget(self.label_login)
        self.label_error = QtWidgets.QLabel(StatusBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error.sizePolicy().hasHeightForWidth())
        self.label_error.setSizePolicy(sizePolicy)
        self.label_error.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout.addWidget(self.label_error)
        self.horizontalLayout.setStretch(0, 1)

        self.retranslateUi(StatusBar)
        QtCore.QMetaObject.connectSlotsByName(StatusBar)

    def retranslateUi(self, StatusBar):
        _translate = QtCore.QCoreApplication.translate
        StatusBar.setWindowTitle(_translate("StatusBar", "Form"))
        self.label_login.setText(_translate("StatusBar", "TextLabel"))
        self.label_error.setText(_translate("StatusBar", "TextLabel"))
