# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\ROS\mediscara_ws\src\mediscara\mediscara\scripts\widgets\layout\collab_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CollabControlWidget(object):
    def setupUi(self, CollabControlWidget):
        CollabControlWidget.setObjectName("CollabControlWidget")
        CollabControlWidget.resize(704, 496)
        CollabControlWidget.setStyleSheet("QLabel {\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(0, 255, 127, 128);\n"
"}\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(CollabControlWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(CollabControlWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label_maintenance = QtWidgets.QLabel(self.groupBox)
        self.label_maintenance.setObjectName("label_maintenance")
        self.gridLayout.addWidget(self.label_maintenance, 1, 1, 1, 2)
        self.button_home = QtWidgets.QPushButton(self.groupBox)
        self.button_home.setMinimumSize(QtCore.QSize(0, 30))
        self.button_home.setObjectName("button_home")
        self.gridLayout.addWidget(self.button_home, 1, 0, 1, 1)
        self.label_pcb_ok = QtWidgets.QLabel(self.groupBox)
        self.label_pcb_ok.setObjectName("label_pcb_ok")
        self.gridLayout.addWidget(self.label_pcb_ok, 2, 2, 1, 1)
        self.label_message = QtWidgets.QLabel(self.groupBox)
        self.label_message.setObjectName("label_message")
        self.gridLayout.addWidget(self.label_message, 4, 0, 1, 3)
        self.label_label_ok = QtWidgets.QLabel(self.groupBox)
        self.label_label_ok.setObjectName("label_label_ok")
        self.gridLayout.addWidget(self.label_label_ok, 3, 2, 1, 1)
        self.button_measure_label = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_measure_label.sizePolicy().hasHeightForWidth())
        self.button_measure_label.setSizePolicy(sizePolicy)
        self.button_measure_label.setMinimumSize(QtCore.QSize(0, 30))
        self.button_measure_label.setObjectName("button_measure_label")
        self.gridLayout.addWidget(self.button_measure_label, 2, 1, 2, 1)
        self.button_end_session = QtWidgets.QPushButton(self.groupBox)
        self.button_end_session.setMinimumSize(QtCore.QSize(0, 30))
        self.button_end_session.setObjectName("button_end_session")
        self.gridLayout.addWidget(self.button_end_session, 0, 2, 1, 1)
        self.button_start_session = QtWidgets.QPushButton(self.groupBox)
        self.button_start_session.setMinimumSize(QtCore.QSize(0, 30))
        self.button_start_session.setObjectName("button_start_session")
        self.gridLayout.addWidget(self.button_start_session, 0, 0, 1, 1)
        self.button_pause = QtWidgets.QPushButton(self.groupBox)
        self.button_pause.setMinimumSize(QtCore.QSize(0, 30))
        self.button_pause.setObjectName("button_pause")
        self.gridLayout.addWidget(self.button_pause, 0, 1, 1, 1)
        self.button_measure_pcb = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_measure_pcb.sizePolicy().hasHeightForWidth())
        self.button_measure_pcb.setSizePolicy(sizePolicy)
        self.button_measure_pcb.setMinimumSize(QtCore.QSize(0, 30))
        self.button_measure_pcb.setObjectName("button_measure_pcb")
        self.gridLayout.addWidget(self.button_measure_pcb, 2, 0, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 3)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(CollabControlWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(CollabControlWidget)
        QtCore.QMetaObject.connectSlotsByName(CollabControlWidget)

    def retranslateUi(self, CollabControlWidget):
        _translate = QtCore.QCoreApplication.translate
        CollabControlWidget.setWindowTitle(_translate("CollabControlWidget", "Form"))
        self.groupBox.setTitle(_translate("CollabControlWidget", "VISION"))
        self.label_maintenance.setText(_translate("CollabControlWidget", "Remaining time: "))
        self.button_home.setText(_translate("CollabControlWidget", "HOME"))
        self.label_pcb_ok.setText(_translate("CollabControlWidget", "TextLabel"))
        self.label_message.setText(_translate("CollabControlWidget", "TextLabel"))
        self.label_label_ok.setText(_translate("CollabControlWidget", "TextLabel"))
        self.button_measure_label.setText(_translate("CollabControlWidget", "Measure Label"))
        self.button_end_session.setText(_translate("CollabControlWidget", "End Session"))
        self.button_start_session.setText(_translate("CollabControlWidget", "Start Session"))
        self.button_pause.setText(_translate("CollabControlWidget", "Pause/Resume"))
        self.button_measure_pcb.setText(_translate("CollabControlWidget", "Measure PCB"))
        self.label_5.setText(_translate("CollabControlWidget", "TextLabel"))
        self.groupBox_2.setTitle(_translate("CollabControlWidget", "MARKING SYSTEM"))
from . import res_rc
