# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\ROS\mediscara_ws\src\mediscara\mediscara\scripts\widgets\layout\collab_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CollabControlWidget(object):
    def setupUi(self, CollabControlWidget):
        CollabControlWidget.setObjectName("CollabControlWidget")
        CollabControlWidget.resize(497, 496)
        CollabControlWidget.setStyleSheet("/* \n"
"    primary color: #6CD2F0\n"
"    primary color dark: #398AA3\n"
"    alternate color: #F0E454\n"
"    alternare color dark: #A39C41\n"
"    accent color: #F03E72\n"
"    background color: #aee2f0\n"
"*/\n"
"\n"
"QPushButton {\n"
"    border: 1px;\n"
"    border-style: outset;\n"
"    border-radius: 7px;\n"
"    border-color: black;\n"
"    background-color: #F0E454;\n"
"    background-color: rgb(240, 228, 84);\n"
"    \n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(240, 228, 84, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px;\n"
"    border-style: outset;\n"
"    border-radius: 7px;\n"
"    border-color: black;\n"
"    background-color: #F0E454;\n"
"    background-color: rgb(240, 228, 84);\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(163, 156, 65, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(CollabControlWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_home_vision = QtWidgets.QPushButton(CollabControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_home_vision.sizePolicy().hasHeightForWidth())
        self.button_home_vision.setSizePolicy(sizePolicy)
        self.button_home_vision.setMinimumSize(QtCore.QSize(0, 60))
        self.button_home_vision.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(92, 212, 76, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(88, 198, 71, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.button_home_vision.setObjectName("button_home_vision")
        self.gridLayout.addWidget(self.button_home_vision, 1, 0, 1, 1)
        self.button_start_marking = QtWidgets.QPushButton(CollabControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start_marking.sizePolicy().hasHeightForWidth())
        self.button_start_marking.setSizePolicy(sizePolicy)
        self.button_start_marking.setMinimumSize(QtCore.QSize(0, 60))
        self.button_start_marking.setObjectName("button_start_marking")
        self.gridLayout.addWidget(self.button_start_marking, 2, 1, 1, 1)
        self.button_home_robotic = QtWidgets.QPushButton(CollabControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_home_robotic.sizePolicy().hasHeightForWidth())
        self.button_home_robotic.setSizePolicy(sizePolicy)
        self.button_home_robotic.setMinimumSize(QtCore.QSize(0, 60))
        self.button_home_robotic.setStyleSheet("QPushButton:!pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(92, 212, 76, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(88, 198, 71, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.button_home_robotic.setObjectName("button_home_robotic")
        self.gridLayout.addWidget(self.button_home_robotic, 1, 1, 1, 1)
        self.button_measure_pcb = QtWidgets.QPushButton(CollabControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_measure_pcb.sizePolicy().hasHeightForWidth())
        self.button_measure_pcb.setSizePolicy(sizePolicy)
        self.button_measure_pcb.setMinimumSize(QtCore.QSize(0, 60))
        self.button_measure_pcb.setObjectName("button_measure_pcb")
        self.gridLayout.addWidget(self.button_measure_pcb, 2, 0, 1, 1)
        self.button_measure_label = QtWidgets.QPushButton(CollabControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_measure_label.sizePolicy().hasHeightForWidth())
        self.button_measure_label.setSizePolicy(sizePolicy)
        self.button_measure_label.setMinimumSize(QtCore.QSize(0, 60))
        self.button_measure_label.setObjectName("button_measure_label")
        self.gridLayout.addWidget(self.button_measure_label, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(CollabControlWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(CollabControlWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(CollabControlWidget)
        self.label_3.setStyleSheet("image: url(:/images/logo);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)

        self.retranslateUi(CollabControlWidget)
        QtCore.QMetaObject.connectSlotsByName(CollabControlWidget)

    def retranslateUi(self, CollabControlWidget):
        _translate = QtCore.QCoreApplication.translate
        CollabControlWidget.setWindowTitle(_translate("CollabControlWidget", "Form"))
        self.button_home_vision.setText(_translate("CollabControlWidget", "HOME"))
        self.button_start_marking.setText(_translate("CollabControlWidget", "START MARKING"))
        self.button_home_robotic.setText(_translate("CollabControlWidget", "HOME"))
        self.button_measure_pcb.setText(_translate("CollabControlWidget", "START MEASURE - PCB"))
        self.button_measure_label.setText(_translate("CollabControlWidget", "START MEASURE - LABEL"))
        self.label.setText(_translate("CollabControlWidget", "Vision"))
        self.label_2.setText(_translate("CollabControlWidget", "Robotic"))
from . import res_rc
