# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\ROS\mediscara_ws\src\mediscara\mediscara\scripts\widgets\layout\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GUIWindow(object):
    def setupUi(self, GUIWindow):
        GUIWindow.setObjectName("GUIWindow")
        GUIWindow.resize(1050, 600)
        GUIWindow.setMinimumSize(QtCore.QSize(1050, 600))
        GUIWindow.setStyleSheet("background-color: #ffffff;")
        self.centralwidget = QtWidgets.QWidget(GUIWindow)
        self.centralwidget.setStyleSheet("/* \n"
"    primary color: #6CD2F0\n"
"    primary color dark: #398AA3\n"
"    alternate color: #F0E454\n"
"    alternare color dark: #A39C41\n"
"    accent color: #F03E72\n"
"    background color: #aee2f0\n"
"*/\n"
"\n"
"QPushButton {\n"
"    border: 1px;\n"
"    border-style: outset;\n"
"    border-radius: 7px;\n"
"    border-color: black;\n"
"    background-color: #F0E454;\n"
"    background-color: rgb(240, 228, 84);\n"
"    \n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(240, 228, 84, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: ;\n"
"    background-color: rgb(163, 156, 65);\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(163, 156, 65, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QTabBar::tab { \n"
"    border: 1px solid black;\n"
"    border-radius: 7px;\n"
"    height: 100px; \n"
"    width: 140px;\n"
"    margin: 6 px;\n"
"    margin-left: 6px;\n"
" }\n"
"QTabBar::tab:selected {\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(57, 138, 163, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    background-color:#6CD2F0;\n"
"    background-color: rgb(108, 210, 240);\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(108, 210, 240, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_container = QtWidgets.QHBoxLayout()
        self.widget_container.setObjectName("widget_container")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.info_widget_layout = QtWidgets.QVBoxLayout(self.tab_info)
        self.info_widget_layout.setObjectName("info_widget_layout")
        self.tabWidget.addTab(self.tab_info, "")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setObjectName("tab_control")
        self.control_widget_layout = QtWidgets.QVBoxLayout(self.tab_control)
        self.control_widget_layout.setObjectName("control_widget_layout")
        self.tabWidget.addTab(self.tab_control, "")
        self.tab_nodes = QtWidgets.QWidget()
        self.tab_nodes.setObjectName("tab_nodes")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_nodes)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.list_nodes = QtWidgets.QListWidget(self.tab_nodes)
        self.list_nodes.setObjectName("list_nodes")
        self.horizontalLayout_3.addWidget(self.list_nodes)
        self.button_refresh = QtWidgets.QPushButton(self.tab_nodes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_refresh.sizePolicy().hasHeightForWidth())
        self.button_refresh.setSizePolicy(sizePolicy)
        self.button_refresh.setStyleSheet("image: url(:/icons/refresh);")
        self.button_refresh.setObjectName("button_refresh")
        self.horizontalLayout_3.addWidget(self.button_refresh)
        self.horizontalLayout_3.setStretch(0, 10)
        self.horizontalLayout_3.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_nodes, "")
        self.tab_grafana = QtWidgets.QWidget()
        self.tab_grafana.setObjectName("tab_grafana")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_grafana)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.web_widget = QtWebEngineWidgets.QWebEngineView(self.tab_grafana)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.web_widget.sizePolicy().hasHeightForWidth())
        self.web_widget.setSizePolicy(sizePolicy)
        self.web_widget.setMinimumSize(QtCore.QSize(1006, 435))
        self.web_widget.setStyleSheet("")
        self.web_widget.setObjectName("web_widget")
        self.verticalLayout_4.addWidget(self.web_widget)
        self.tabWidget.addTab(self.tab_grafana, "")
        self.tab_error = QtWidgets.QWidget()
        self.tab_error.setObjectName("tab_error")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_error)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.list_error = QtWidgets.QListWidget(self.tab_error)
        self.list_error.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.list_error.setObjectName("list_error")
        self.horizontalLayout_4.addWidget(self.list_error)
        self.button_clear_errors = QtWidgets.QPushButton(self.tab_error)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear_errors.sizePolicy().hasHeightForWidth())
        self.button_clear_errors.setSizePolicy(sizePolicy)
        self.button_clear_errors.setObjectName("button_clear_errors")
        self.horizontalLayout_4.addWidget(self.button_clear_errors)
        self.horizontalLayout_4.setStretch(0, 10)
        self.horizontalLayout_4.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_error, "")
        self.tab_login = QtWidgets.QWidget()
        self.tab_login.setObjectName("tab_login")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(16, 16, 16, -1)
        self.formLayout.setSpacing(16)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.tab_login)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.line_edit_name = QtWidgets.QLineEdit(self.tab_login)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_edit_name.setFont(font)
        self.line_edit_name.setObjectName("line_edit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_edit_name)
        self.line_edit_pass = QtWidgets.QLineEdit(self.tab_login)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_edit_pass.setFont(font)
        self.line_edit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_pass.setObjectName("line_edit_pass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_edit_pass)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_login = QtWidgets.QLabel(self.tab_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_login.sizePolicy().hasHeightForWidth())
        self.label_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_login.setText("")
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_login = QtWidgets.QPushButton(self.tab_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_login.sizePolicy().hasHeightForWidth())
        self.button_login.setSizePolicy(sizePolicy)
        self.button_login.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_login.setFont(font)
        self.button_login.setStyleSheet("QPushButton {\n"
"    background-color: #5CD44C;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(92, 212, 76, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #58c647;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(88, 198, 71, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.button_login.setObjectName("button_login")
        self.horizontalLayout_2.addWidget(self.button_login)
        self.button_logout = QtWidgets.QPushButton(self.tab_login)
        self.button_logout.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_logout.setFont(font)
        self.button_logout.setStyleSheet("QPushButton {\n"
"    background-color: #F03E72;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(240, 62, 114, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d83868;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(216, 56, 104, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.button_logout.setObjectName("button_logout")
        self.horizontalLayout_2.addWidget(self.button_logout)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.tabWidget.addTab(self.tab_login, "")
        self.widget_container.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.widget_container)
        self.horizontalLayout.setStretch(0, 6)
        GUIWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GUIWindow)
        self.statusbar.setObjectName("statusbar")
        GUIWindow.setStatusBar(self.statusbar)
        self.actionSt_tusz = QtWidgets.QAction(GUIWindow)
        self.actionSt_tusz.setObjectName("actionSt_tusz")
        self.label.setBuddy(self.line_edit_name)
        self.label_2.setBuddy(self.line_edit_pass)

        self.retranslateUi(GUIWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(GUIWindow)
        GUIWindow.setTabOrder(self.line_edit_name, self.line_edit_pass)
        GUIWindow.setTabOrder(self.line_edit_pass, self.tabWidget)

    def retranslateUi(self, GUIWindow):
        _translate = QtCore.QCoreApplication.translate
        GUIWindow.setWindowTitle(_translate("GUIWindow", "GUI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_info), _translate("GUIWindow", "INFO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_control), _translate("GUIWindow", "CONTROL"))
        self.button_refresh.setText(_translate("GUIWindow", "RELOAD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_nodes), _translate("GUIWindow", "NODES"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_grafana), _translate("GUIWindow", "GRAFANA"))
        self.button_clear_errors.setText(_translate("GUIWindow", "CLEAR ERRORS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_error), _translate("GUIWindow", "ERROR LOG"))
        self.label.setText(_translate("GUIWindow", "Username"))
        self.label_2.setText(_translate("GUIWindow", "Password"))
        self.button_login.setText(_translate("GUIWindow", "LOGIN"))
        self.button_logout.setText(_translate("GUIWindow", "LOGOUT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_login), _translate("GUIWindow", "LOGIN"))
        self.actionSt_tusz.setText(_translate("GUIWindow", "Státusz"))
from PyQt5 import QtWebEngineWidgets
