# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\ROS\mediscara_ws\src\mediscara\mediscara\scripts\widgets\layout\list_widget_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListItem(object):
    def setupUi(self, ListItem):
        ListItem.setObjectName("ListItem")
        ListItem.resize(523, 31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ListItem.sizePolicy().hasHeightForWidth())
        ListItem.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ListItem)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ListItem)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_node_name = QtWidgets.QLabel(ListItem)
        self.label_node_name.setObjectName("label_node_name")
        self.horizontalLayout.addWidget(self.label_node_name)
        self.label_2 = QtWidgets.QLabel(ListItem)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_error_message = QtWidgets.QLabel(ListItem)
        self.label_error_message.setObjectName("label_error_message")
        self.horizontalLayout.addWidget(self.label_error_message)
        self.label_3 = QtWidgets.QLabel(ListItem)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_error_code = QtWidgets.QLabel(ListItem)
        self.label_error_code.setObjectName("label_error_code")
        self.horizontalLayout.addWidget(self.label_error_code)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(5, 1)

        self.retranslateUi(ListItem)
        QtCore.QMetaObject.connectSlotsByName(ListItem)

    def retranslateUi(self, ListItem):
        _translate = QtCore.QCoreApplication.translate
        ListItem.setWindowTitle(_translate("ListItem", "Form"))
        self.label.setText(_translate("ListItem", "Node name:"))
        self.label_node_name.setText(_translate("ListItem", "TextLabel"))
        self.label_2.setText(_translate("ListItem", "Error message:"))
        self.label_error_message.setText(_translate("ListItem", "TextLabel"))
        self.label_3.setText(_translate("ListItem", "Error code"))
        self.label_error_code.setText(_translate("ListItem", "TextLabel"))
