# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\ROS\mediscara_ws\src\mediscara\mediscara\scripts\widgets\layout\node_list_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NodeListItem(object):
    def setupUi(self, NodeListItem):
        NodeListItem.setObjectName("NodeListItem")
        NodeListItem.resize(443, 57)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NodeListItem.sizePolicy().hasHeightForWidth())
        NodeListItem.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(NodeListItem)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_node_name = QtWidgets.QLabel(NodeListItem)
        self.label_node_name.setStyleSheet("QLabel {\n"
"    padding: 12px;\n"
"    border: 1px solid black;\n"
"    border-radius: 7px;\n"
"}")
        self.label_node_name.setObjectName("label_node_name")
        self.verticalLayout.addWidget(self.label_node_name)

        self.retranslateUi(NodeListItem)
        QtCore.QMetaObject.connectSlotsByName(NodeListItem)

    def retranslateUi(self, NodeListItem):
        _translate = QtCore.QCoreApplication.translate
        NodeListItem.setWindowTitle(_translate("NodeListItem", "Form"))
        self.label_node_name.setText(_translate("NodeListItem", "TextLabel"))
